### ISSUE TITLE
Put everything together

### ISSUE THREAD

**Issue by LFrancis23** [ECE473-2021/mips_cpu#26]
Let me know when everything is in main branch and I will put together the bdf.

**Comment by ryankinney33** [comment]
To fix LUI instructions:
1. Replace the Shamtmux with a 3x1 mux
2. Connect a bus that always contains 16 to the remaining input.
    - This can be done by naming the bus that connects to it `ground[31..5],high[4],ground[3..0]`.
3. The final part is modifying the controller to have a 2 bit shift selecting signal, instead of 1 bit.
    - The ID_EX pipeline register will need to be updated to have the ID_ALUASrc and EX_ALUASrc be two bits as well.

**Comment by ryankinney33** [comment]
Other small additions that need to be done include changing the PC to have a WriteEnable line that would be controlled by the hazard detection unit.
